// This file is Copyright its original authors, visible in version control
// history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE
// or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// You may not use this file except in accordance with one or both of these
// licenses.

//! Encrypted payment tokens for point-of-sale offers.
//!
//! A point-of-sale (PoS) device constructing a per-order offer from a merchant-provided template
//! seals the order fields -- amount, description, and a per-order secret `order_id` -- into a
//! `payment_token` encrypted to the offer's signing pubkey. Only the merchant can decrypt the
//! token. At invoice-request time the merchant verifies the token's amount and description against
//! the mirrored offer fields, and at payment time it relays the `order_id` in its payment
//! notification, which is what authenticates the notification to the PoS.
//!
//! The token is encrypted using an ephemeral key per order, so token ciphertexts cannot be linked
//! to the merchant key across offers.
//!
//! See [bLIP 56](https://github.com/lightning/blips/pull/56) for more information.

use bitcoin::secp256k1::ecdh::SharedSecret;
use bitcoin::secp256k1::{self, PublicKey, Secp256k1, SecretKey};

use crate::crypto::streams::{ChaChaPolyReadAdapter, ChaChaPolyWriteAdapter};
use crate::io::Cursor;
use crate::prelude::*;
use crate::sign::EntropySource;
use crate::util::ser::{FixedLengthReader, LengthReadableArgs, Writeable};

use core::ops::Deref;

/// The minimum length in bytes of a payment token's `order_id`.
///
/// The `order_id` authenticates payment notifications, so it must carry enough entropy that a
/// customer holding the offer cannot guess it.
pub const MIN_ORDER_ID_LEN: usize = 16;

/// The length in bytes of the ephemeral public key prefixed to an encrypted payment token.
const EPHEMERAL_PUBKEY_LEN: usize = 33;

/// The length in bytes of the Poly1305 authentication tag appended to an encrypted payment token.
const TAG_LEN: usize = 16;

/// The order fields sealed into an offer's `payment_token`.
///
/// The point-of-sale device commits to these fields when constructing a per-order offer. The
/// merchant decrypts them at invoice-request time and must reject the request if `amount_msats`
/// or `description` do not match the mirrored offer fields.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PaymentTokenPayload {
	/// The amount in millisatoshis set on the per-order offer.
	pub amount_msats: u64,
	/// The description set on the per-order offer, if any.
	pub description: Option<String>,
	/// The per-order secret generated by the point-of-sale device, relayed by the merchant in its
	/// payment notification. Must be at least [`MIN_ORDER_ID_LEN`] bytes.
	pub order_id: Vec<u8>,
}

impl_ser_tlv_based!(PaymentTokenPayload, {
	(0, amount_msats, required),
	(2, description, option),
	(4, order_id, required_vec),
});

impl PaymentTokenPayload {
	/// Encrypts the payload to the given public key, producing an opaque payment token.
	///
	/// The token format is `ephemeral_pubkey (33 bytes) || ciphertext || tag (16 bytes)`. A fresh
	/// ephemeral key is drawn from `entropy_source` for each token so that ciphertexts cannot be
	/// linked to `recipient_pubkey` across offers.
	pub fn encrypt<ES: Deref, T: secp256k1::Signing>(
		&self, recipient_pubkey: &PublicKey, entropy_source: ES, secp_ctx: &Secp256k1<T>,
	) -> Vec<u8>
	where
		ES::Target: EntropySource,
	{
		let ephemeral_secret_bytes = entropy_source.get_secure_random_bytes();
		let ephemeral_secret =
			SecretKey::from_slice(&ephemeral_secret_bytes).expect("Valid secret key");
		let ephemeral_pubkey = PublicKey::from_secret_key(secp_ctx, &ephemeral_secret);
		let rho = SharedSecret::new(recipient_pubkey, &ephemeral_secret).secret_bytes();

		let write_adapter = ChaChaPolyWriteAdapter::new(rho, self);
		let mut token =
			Vec::with_capacity(EPHEMERAL_PUBKEY_LEN + write_adapter.serialized_length());
		token.extend_from_slice(&ephemeral_pubkey.serialize());
		write_adapter.write(&mut token).expect("writing to a Vec never fails");
		token
	}

	/// Decrypts a payment token using the secret key corresponding to the public key it was
	/// encrypted to.
	///
	/// Errors if the token is malformed, fails to authenticate, or contains an `order_id` shorter
	/// than [`MIN_ORDER_ID_LEN`] bytes.
	pub fn decrypt(recipient_secret_key: &SecretKey, token: &[u8]) -> Result<Self, ()> {
		if token.len() < EPHEMERAL_PUBKEY_LEN + TAG_LEN {
			return Err(());
		}

		let ephemeral_pubkey =
			PublicKey::from_slice(&token[..EPHEMERAL_PUBKEY_LEN]).map_err(|_| ())?;
		let rho = SharedSecret::new(&ephemeral_pubkey, recipient_secret_key).secret_bytes();

		let encrypted_payload = &token[EPHEMERAL_PUBKEY_LEN..];
		let mut cursor = Cursor::new(encrypted_payload);
		let mut reader = FixedLengthReader::new(&mut cursor, encrypted_payload.len() as u64);
		let payload: PaymentTokenPayload =
			match ChaChaPolyReadAdapter::<PaymentTokenPayload>::read(&mut reader, rho) {
				Ok(ChaChaPolyReadAdapter { readable }) => readable,
				Err(_) => return Err(()),
			};

		if payload.order_id.len() < MIN_ORDER_ID_LEN {
			return Err(());
		}

		Ok(payload)
	}
}

#[cfg(test)]
mod tests {
	use super::{PaymentTokenPayload, MIN_ORDER_ID_LEN};
	use crate::prelude::*;
	use crate::util::test_utils::TestKeysInterface;
	use bitcoin::network::Network;
	use bitcoin::secp256k1::{PublicKey, Secp256k1, SecretKey};

	fn payload() -> PaymentTokenPayload {
		PaymentTokenPayload {
			amount_msats: 50_000,
			description: Some("coffee, large".to_string()),
			order_id: vec![42; MIN_ORDER_ID_LEN],
		}
	}

	#[test]
	fn encrypts_and_decrypts_payment_token() {
		let secp_ctx = Secp256k1::new();
		let entropy = TestKeysInterface::new(&[41; 32], Network::Testnet);
		let recipient_secret_key = SecretKey::from_slice(&[42; 32]).unwrap();
		let recipient_pubkey = PublicKey::from_secret_key(&secp_ctx, &recipient_secret_key);

		let token = payload().encrypt(&recipient_pubkey, &entropy, &secp_ctx);
		let decrypted = PaymentTokenPayload::decrypt(&recipient_secret_key, &token).unwrap();
		assert_eq!(decrypted, payload());
	}

	#[test]
	fn fails_decrypting_with_wrong_key() {
		let secp_ctx = Secp256k1::new();
		let entropy = TestKeysInterface::new(&[41; 32], Network::Testnet);
		let recipient_secret_key = SecretKey::from_slice(&[42; 32]).unwrap();
		let recipient_pubkey = PublicKey::from_secret_key(&secp_ctx, &recipient_secret_key);

		let token = payload().encrypt(&recipient_pubkey, &entropy, &secp_ctx);
		let wrong_key = SecretKey::from_slice(&[43; 32]).unwrap();
		assert!(PaymentTokenPayload::decrypt(&wrong_key, &token).is_err());
	}

	#[test]
	fn fails_decrypting_tampered_token() {
		let secp_ctx = Secp256k1::new();
		let entropy = TestKeysInterface::new(&[41; 32], Network::Testnet);
		let recipient_secret_key = SecretKey::from_slice(&[42; 32]).unwrap();
		let recipient_pubkey = PublicKey::from_secret_key(&secp_ctx, &recipient_secret_key);

		let mut token = payload().encrypt(&recipient_pubkey, &entropy, &secp_ctx);
		let len = token.len();
		token[len - 20] ^= 1;
		assert!(PaymentTokenPayload::decrypt(&recipient_secret_key, &token).is_err());
	}

	#[test]
	fn fails_decrypting_truncated_token() {
		let recipient_secret_key = SecretKey::from_slice(&[42; 32]).unwrap();
		assert!(PaymentTokenPayload::decrypt(&recipient_secret_key, &[0; 48]).is_err());
	}

	#[test]
	fn fails_decrypting_token_with_short_order_id() {
		let secp_ctx = Secp256k1::new();
		let entropy = TestKeysInterface::new(&[41; 32], Network::Testnet);
		let recipient_secret_key = SecretKey::from_slice(&[42; 32]).unwrap();
		let recipient_pubkey = PublicKey::from_secret_key(&secp_ctx, &recipient_secret_key);

		let short_payload = PaymentTokenPayload {
			amount_msats: 50_000,
			description: None,
			order_id: vec![42; MIN_ORDER_ID_LEN - 1],
		};
		let token = short_payload.encrypt(&recipient_pubkey, &entropy, &secp_ctx);
		assert!(PaymentTokenPayload::decrypt(&recipient_secret_key, &token).is_err());
	}

	#[test]
	fn tokens_for_same_payload_are_unlinkable() {
		let secp_ctx = Secp256k1::new();
		let entropy = TestKeysInterface::new(&[41; 32], Network::Testnet);
		let recipient_secret_key = SecretKey::from_slice(&[42; 32]).unwrap();
		let recipient_pubkey = PublicKey::from_secret_key(&secp_ctx, &recipient_secret_key);

		let token_a = payload().encrypt(&recipient_pubkey, &entropy, &secp_ctx);
		let token_b = payload().encrypt(&recipient_pubkey, &entropy, &secp_ctx);
		assert_ne!(token_a, token_b);
	}
}
